apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  refreshInterval: 1m

  conditions:
    - namespaces:
        - external-secrets
        - argocd
        - redis

  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: secret
      version: v2

      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets

          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
            audiences:
              - vault
