apiVersion: v1
kind: Secret
metadata:
  name: repo-rke2-gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:<GITHUB_USERNAME>/rke2-gitops.git
  sshPrivateKey: |
    <ARGOCD_READ_ONLY_DEPLOY_KEY_PRIVATE_PART>
