apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  generators:
  - git:
      repoURL: git@github.com:bertughas123/rke2-gitops.git
      revision: main
      files:
      - path: platform-manifests/*/source.yaml
  template:
    metadata:
      name: platform-manifests-{{.name}}
    spec:
      project: platform
      source:
        repoURL: git@github.com:bertughas123/rke2-gitops.git
        targetRevision: main
        path: "{{.manifestPath}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  syncPolicy:
    preserveResourcesOnDeletion: true
