apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/rancher/rke2/storage/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rke2-server
