apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repository
  namespace: argocd
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m

  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore

  target:
    name: repo-rke2-gitops
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:bertughas123/rke2-gitops.git
        sshPrivateKey: "{{ .sshPrivateKey }}"

  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: gitops/argocd/repository
        property: sshPrivateKey
