apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m

  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore

  target:
    name: redis-auth
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: redis-password
      remoteRef:
        key: platform/redis/auth
        property: password
