apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phase5-test
  namespace: external-secrets
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m

  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore

  target:
    name: phase5-test
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: message
      remoteRef:
        key: phase5/test
        property: value
