apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  project: platform
  source:
    repoURL: git@github.com:bertughas123/rke2-gitops.git
    targetRevision: main
    path: platform-manifests/external-secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
